#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SysMonMS.Resource", IsApplication=true)]

namespace SysMonMS
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int btn_cancel = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int btn_connect = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int btn_list = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int et_address = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int et_port = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int lv_list = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int tv_status = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int tv_title = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int webView_detail = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int adapter = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Detail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int List = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
